# Generated by Django 6.0.3 on 2026-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_product_created_at_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='brand', max_length=100),
            preserve_default=False,
        ),
    ]
