# Generated by Django 6.0.3 on 2026-04-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='manager',
            new_name='created_by',
        ),
    ]
