# Generated by Django 6.0.3 on 2026-04-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_rename_manager_category_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active_flag',
            new_name='is_active',
        ),
    ]
