# Generated by Django 6.0.3 on 2026-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0013_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
