# Generated by Django 6.0.3 on 2026-04-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0014_product_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
