# Generated by Django 6.0.4 on 2026-04-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0015_remove_product_sort_order_productimage_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order']},
        ),
    ]
