# Generated by Django 6.0.3 on 2026-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0010_alter_product_created_by_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(default='qweqwe', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
