# Generated by Django 6.0.3 on 2026-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0012_productimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='qewqe', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
